name: Armar APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar herramientas del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          
      - name: Instalar Buildozer
        run: pip install --user --upgrade buildozer cython virtualenv
        
      - name: Cocinar el APK
        run: |
          export PATH=$PATH:~/.local/bin
          yes | buildozer -y android debug
          
      - name: Guardar el APK final
        uses: actions/upload-artifact@v4
        with:
          name: MiApp_Recetario
          path: bin/*.apk
